version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: America/New_York
  groups:
    bundler:
      patterns:
        - "*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: America/New_York
  groups:
    github_actions:
      patterns:
        - "*"
